-- MySQL Script generated by MySQL Workbench
-- Tue Mar 26 08:54:43 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Information`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Information` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Information` (
  `idInformation` INT NOT NULL AUTO_INCREMENT,
  `Tel` INT(9) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idInformation`),
  UNIQUE INDEX `idInformation_UNIQUE` (`idInformation` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(90) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Picture` VARCHAR(100) NOT NULL,
  `Information_idInformation` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) VISIBLE,
  UNIQUE INDEX `UserName_UNIQUE` (`UserName` ASC) VISIBLE,
  INDEX `fk_User_Information1_idx` (`Information_idInformation` ASC) VISIBLE,
  CONSTRAINT `fk_User_Information1`
    FOREIGN KEY (`Information_idInformation`)
    REFERENCES `mydb`.`Information` (`idInformation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Description`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Description` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Description` (
  `idDescription` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(1500) NOT NULL,
  PRIMARY KEY (`idDescription`),
  UNIQUE INDEX `idDescription_UNIQUE` (`idDescription` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HowLong`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`HowLong` ;

CREATE TABLE IF NOT EXISTS `mydb`.`HowLong` (
  `idHowLong` INT NOT NULL AUTO_INCREMENT,
  `HowLong` VARCHAR(45) NOT NULL,
  `Eps` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idHowLong`),
  UNIQUE INDEX `idHowLong_UNIQUE` (`idHowLong` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Anime`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Anime` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Anime` (
  `idAnime` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Picture` VARCHAR(100) NOT NULL,
  `Description_idDescription` INT NOT NULL,
  `HowLong_idHowLong` INT NOT NULL,
  PRIMARY KEY (`idAnime`),
  UNIQUE INDEX `idAnime_UNIQUE` (`idAnime` ASC) VISIBLE,
  INDEX `fk_Anime_Description_idx` (`Description_idDescription` ASC) VISIBLE,
  INDEX `fk_Anime_HowLong1_idx` (`HowLong_idHowLong` ASC) VISIBLE,
  CONSTRAINT `fk_Anime_Description`
    FOREIGN KEY (`Description_idDescription`)
    REFERENCES `mydb`.`Description` (`idDescription`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anime_HowLong1`
    FOREIGN KEY (`HowLong_idHowLong`)
    REFERENCES `mydb`.`HowLong` (`idHowLong`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Genre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Genre` (
  `idGenre` INT NOT NULL AUTO_INCREMENT,
  `GName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGenre`),
  UNIQUE INDEX `idGenre_UNIQUE` (`idGenre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Review` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Review` (
  `idReview` INT NOT NULL AUTO_INCREMENT,
  `Review` VARCHAR(500) NOT NULL,
  `Stars` VARCHAR(45) NOT NULL,
  `Anime_idAnime` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idReview`, `Anime_idAnime`, `User_idUser`),
  UNIQUE INDEX `idReview_UNIQUE` (`idReview` ASC) VISIBLE,
  INDEX `fk_Review_Anime1_idx` (`Anime_idAnime` ASC) VISIBLE,
  INDEX `fk_Review_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Review_Anime1`
    FOREIGN KEY (`Anime_idAnime`)
    REFERENCES `mydb`.`Anime` (`idAnime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Review_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Anime_has_Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Anime_has_Genre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Anime_has_Genre` (
  `Anime_idAnime` INT NOT NULL,
  `Genre_idGenre` INT NOT NULL,
  PRIMARY KEY (`Anime_idAnime`, `Genre_idGenre`),
  INDEX `fk_Anime_has_Genre_Genre1_idx` (`Genre_idGenre` ASC) VISIBLE,
  INDEX `fk_Anime_has_Genre_Anime1_idx` (`Anime_idAnime` ASC) VISIBLE,
  CONSTRAINT `fk_Anime_has_Genre_Anime1`
    FOREIGN KEY (`Anime_idAnime`)
    REFERENCES `mydb`.`Anime` (`idAnime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anime_has_Genre_Genre1`
    FOREIGN KEY (`Genre_idGenre`)
    REFERENCES `mydb`.`Genre` (`idGenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_has_Anime`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User_has_Anime` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User_has_Anime` (
  `User_idUser` INT NOT NULL,
  `Anime_idAnime` INT NOT NULL,
  PRIMARY KEY (`User_idUser`, `Anime_idAnime`),
  INDEX `fk_User_has_Anime_Anime1_idx` (`Anime_idAnime` ASC) VISIBLE,
  INDEX `fk_User_has_Anime_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Anime_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Anime_Anime1`
    FOREIGN KEY (`Anime_idAnime`)
    REFERENCES `mydb`.`Anime` (`idAnime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
