-- MySQL Script generated by MySQL Workbench
-- Mon Feb 12 09:28:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Information` (
  `idInformation` INT NOT NULL AUTO_INCREMENT,
  `Tel` VARCHAR(45) NOT NULL,
  `Location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idInformation`),
  UNIQUE INDEX `idInformation_UNIQUE` (`idInformation` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genre` (
  `idGenre` INT NOT NULL AUTO_INCREMENT,
  `GName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGenre`),
  UNIQUE INDEX `idGenre_UNIQUE` (`idGenre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Review` (
  `idReview` INT NOT NULL AUTO_INCREMENT,
  `Review` VARCHAR(500) NOT NULL,
  `Stars` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idReview`),
  UNIQUE INDEX `idReview_UNIQUE` (`idReview` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HowLong`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HowLong` (
  `idHowLong` INT NOT NULL AUTO_INCREMENT,
  `HowLong` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idHowLong`),
  UNIQUE INDEX `idHowLong_UNIQUE` (`idHowLong` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Description` (
  `idDescription` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idDescription`),
  UNIQUE INDEX `idDescription_UNIQUE` (`idDescription` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Anime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Anime` (
  `idAnime` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Genre_idGenre` INT NOT NULL,
  `Review_idReview` INT NOT NULL,
  `HowLong_idHowLong` INT NOT NULL,
  `Description_idDescription` INT NOT NULL,
  PRIMARY KEY (`idAnime`, `Genre_idGenre`, `Review_idReview`, `HowLong_idHowLong`, `Description_idDescription`),
  UNIQUE INDEX `idAnime_UNIQUE` (`idAnime` ASC) VISIBLE,
  INDEX `fk_Anime_Genre1_idx` (`Genre_idGenre` ASC) VISIBLE,
  INDEX `fk_Anime_Review1_idx` (`Review_idReview` ASC) VISIBLE,
  INDEX `fk_Anime_HowLong1_idx` (`HowLong_idHowLong` ASC) VISIBLE,
  INDEX `fk_Anime_Description1_idx` (`Description_idDescription` ASC) VISIBLE,
  CONSTRAINT `fk_Anime_Genre1`
    FOREIGN KEY (`Genre_idGenre`)
    REFERENCES `mydb`.`Genre` (`idGenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anime_Review1`
    FOREIGN KEY (`Review_idReview`)
    REFERENCES `mydb`.`Review` (`idReview`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anime_HowLong1`
    FOREIGN KEY (`HowLong_idHowLong`)
    REFERENCES `mydb`.`HowLong` (`idHowLong`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anime_Description1`
    FOREIGN KEY (`Description_idDescription`)
    REFERENCES `mydb`.`Description` (`idDescription`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(90) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Information_idInformation` INT NOT NULL,
  `Anime_idAnime` INT NOT NULL,
  `Anime_Genre_idGenre` INT NOT NULL,
  `Anime_Review_idReview` INT NOT NULL,
  PRIMARY KEY (`idUser`, `Information_idInformation`, `Anime_idAnime`, `Anime_Genre_idGenre`, `Anime_Review_idReview`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) VISIBLE,
  INDEX `fk_User_Information_idx` (`Information_idInformation` ASC) VISIBLE,
  INDEX `fk_User_Anime1_idx` (`Anime_idAnime` ASC, `Anime_Genre_idGenre` ASC, `Anime_Review_idReview` ASC) VISIBLE,
  CONSTRAINT `fk_User_Information`
    FOREIGN KEY (`Information_idInformation`)
    REFERENCES `mydb`.`Information` (`idInformation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Anime1`
    FOREIGN KEY (`Anime_idAnime` , `Anime_Genre_idGenre` , `Anime_Review_idReview`)
    REFERENCES `mydb`.`Anime` (`idAnime` , `Genre_idGenre` , `Review_idReview`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
